# name of the pipeline:
name: Playwright Tests
# when it runs...
on: 
# every git push on the named branch GitHub actions pipeline will run it
  push: 
    branch: [ main ]
# runs "jobs"
jobs:
  playwrighttests:
# which operating system to run on...
    runs-on: ubuntu-latest # using Linux as commonly used in programming
# action steps
    steps:
#  name of step 1
      - name: Checkout repository
# declares which github action to use
        uses: actions/checkout@v2
#  name of step 2
      - name: Say hello
        run: echo Hello
